// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApJyv2G1Pz_6UO9QiRFxvpBH7kT01P8Dw',
    appId: '1:405166675189:web:3202f7016304165121a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    authDomain: 'mono-firebase.firebaseapp.com',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
    measurementId: 'G-88BNG7KQZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrk4rls6KWZOg1tWQyveuHWSHJD17NSfI',
    appId: '1:405166675189:android:d0d6711bce5096d221a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo-hfsH_AG8XsENm4upBsiiR61Zoy8MKo',
    appId: '1:405166675189:ios:92e860abe442f25a21a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
    iosClientId:
        '405166675189-jseescbja9pqljjeql8r0b5ktvbfs0gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo-hfsH_AG8XsENm4upBsiiR61Zoy8MKo',
    appId: '1:405166675189:ios:92e860abe442f25a21a1bc',
    messagingSenderId: '405166675189',
    projectId: 'mono-firebase',
    databaseURL: 'https://mono-firebase.firebaseio.com',
    storageBucket: 'mono-firebase.appspot.com',
    iosClientId:
        '405166675189-jseescbja9pqljjeql8r0b5ktvbfs0gp.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
